### ISSUE TITLE
Support Event API 

### ISSUE THREAD

**Issue by joshowen** [newrelic/newrelic-telemetry-sdk-node#28]
We would like to use the Event API, which is only currently supported in the python telemetry sdk.  This is useful for projects using high security mode in the APM agent, but still need to publish custom events.

**Comment by michaelgoin** [comment]
@joshowen Thank you for the request!

**Comment by michaelgoin** [comment]
"The Telemetry SDK implements an abstraction for sending custom events that follows the data model convention for spans and metrics."

https://github.com/newrelic/newrelic-telemetry-sdk-specs/blob/master/capabilities.md#events
