### ISSUE TITLE
Clarify deprecation comments

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/newrelic-telemetry-sdk-node#71]
Can we clarify this comment in the readme file:

> In the next 3-6 months, we plan to EOL the New Relic Node.js Telemetry SDK. If you are using the Telemetry SDK to send OpenTelemetry data to New Relic, we recommend using the OpenTelemetry Collector with the New Relic Exporter as an alternative. You can find an example [here](https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/collector/nr-exporter-docker).

There are a lot of customers looking to implement custom metrics for New Relic that are not using OTEL and do not have the time to invest in OTEL.  Also this deprecation intent/scope is not noted anywhere on the public docs site.

**Comment by coreyarnold** [comment]
@GaPeppy The utilization of the Node.js Telemetry SDK doesn't warrant continued support at this time in lieu of other efforts the team has on their roadmap. Unless priorities changes, we are still looking to EOL this SDK in the near future, as early as Q1 (Apr-Jun). Please feel free to reach out directly if you would like to discuss further.

Thanks,
Corey

**Comment by InesNi** [comment]
Hello, 

I am looking to use the Node.js Telemetry SDK as New Relic docs point to use this for my use case, but saw the deprecation comment noted in this issue. 
I see by the dates here that it was supposed to be EOL about a year ago, but it is still here and the New Relic docs still point to using this SDK, and are not mentioning this deprecation anywhere.
Naturally my question is can/should I still use this SDK or are you still planning to EOL?

Thank you,
Nidhi

**Comment by mrickard** [comment]
@InesNi This repo hasn't been touched in quite a while, and will be EOL'd. We'll update the docs to note that.
